spring.application.name=mechanics-api

spring.datasource.url=jdbc:postgresql://localhost:5432/oficina_db
spring.datasource.username=oficina_user
spring.datasource.password=oficina_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:chave-local-mvp-123456789012345678901234567890}

server.port=8080